name: Miss Red Pen
favicon: null
layout_spectrum: 0.76135
typography_spectrum: 0.86589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e6f71'
    - '#a42231'
    - '#000000'
    - '#ffffff'
    - '#0000ff'
  brandStrength: 0.6875
  lightness: 0.8784831180237234
  saturation: 0.4524694390129298
  rhythmicContrast: 0.2086447279434651
purpose: []
